#!/usr/bin/env bash
# Probe GPU / Vulkan / VRAM and pick a NeonArena gfx preset: low | med | high.
# Does not launch the engine. Used by start-quake3e.sh.
set -euo pipefail

usage() {
  cat <<EOF
Usage:
  $0                print preset (low|med|high)
  $0 --dump         print probe details + preset
  $0 --ensure FILE  write FILE if missing, then print preset
  $0 --write FILE PRESET
  $0 --help
EOF
  exit 0
}

have_vulkan() {
  local d
  for d in /usr/share/vulkan/icd.d /etc/vulkan/icd.d \
           "${HOME:-}/.local/share/vulkan/icd.d" /usr/lib/x86_64-linux-gnu/vulkan/icd.d; do
    [ -d "$d" ] || continue
    if ls "$d"/*.json >/dev/null 2>&1; then
      return 0
    fi
  done
  if command -v vulkaninfo >/dev/null 2>&1; then
    vulkaninfo --summary >/dev/null 2>&1 && return 0
  fi
  return 1
}

gpu_name() {
  local n=""
  if command -v lspci >/dev/null 2>&1; then
    n=$(lspci 2>/dev/null | grep -iE 'VGA compatible controller|3D controller|Display controller' | head -1 || true)
  fi
  if [ -z "$n" ] && [ -r /sys/class/drm/card0/device/vendor ]; then
    n="drm vendor=$(cat /sys/class/drm/card0/device/vendor 2>/dev/null) device=$(cat /sys/class/drm/card0/device/device 2>/dev/null)"
  fi
  printf '%s' "$n"
}

vram_mb() {
  local mb="" line
  if command -v nvidia-smi >/dev/null 2>&1; then
    mb=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ' || true)
  fi
  if [ -z "$mb" ]; then
    for line in /sys/class/drm/card*/device/mem_info_vram_total; do
      [ -r "$line" ] || continue
      mb=$(awk '{printf "%d", $1/1024/1024}' "$line" 2>/dev/null || true)
      [ -n "$mb" ] && break
    done
  fi
  printf '%s' "${mb:-0}"
}

pick_preset() {
  local name="$1" vulkan="$2" vram="$3"

  echo "$name" | grep -qiE 'llvmpipe|softpipe|swiftshader|microsoft basic' && {
    echo low
    return
  }

  if [ "$vulkan" != 1 ]; then
    echo low
    return
  fi

  if echo "$name" | grep -qiE 'Intel.*(UHD|HD Graphics)|Radeon Graphics$|Picasso|Raven Ridge|Vega 3|Vega 8|Vega 11'; then
    echo med
    return
  fi

  if [ "$vram" -ge 6144 ] 2>/dev/null; then
    echo high
    return
  fi

  if echo "$name" | grep -qiE 'RTX |GTX 16|GTX 1070|GTX 1080|GTX 1660|RX 5[567]0|RX 6[5678]|RX 7[67]|RX 7600|RX 7700|RX 7800|RX 7900|Arc A|Arc B'; then
    echo high
    return
  fi

  echo med
}

preset_body() {
  local preset="$1" name="$2"
  cat <<EOF
// NeonArena auto gfx — generated by scripts/detect-gfx.sh
// preset: $preset
// gpu: $name
// Delete this file (or pass --gfx-reset) to probe again.

EOF
  case "$preset" in
    high)
      cat <<'EOF'
seta cl_renderer "vulkan"
seta r_bloom "1"
seta r_bloom_intensity "0.5"
seta r_bloom_threshold "0.6"
seta r_picmip "0"
seta r_ext_max_anisotropy "8"
seta r_texturemode "GL_LINEAR_MIPMAP_LINEAR"
seta r_dynamiclight "1"
seta r_flares "1"
seta r_fastsky "0"
seta r_vertexlight "0"
seta cg_shadows "1"
seta r_subdivisions "4"
seta com_maxfps "250"
seta r_swapInterval "0"
echo "^4NeonArena ^7gfx auto: HIGH"
EOF
      ;;
    low)
      cat <<'EOF'
seta cl_renderer "opengl"
seta r_bloom "0"
seta r_picmip "2"
seta r_ext_max_anisotropy "1"
seta r_dynamiclight "0"
seta r_flares "0"
seta r_fastsky "1"
seta r_vertexlight "1"
seta cg_shadows "0"
seta r_subdivisions "20"
seta com_maxfps "125"
seta r_swapInterval "1"
echo "^4NeonArena ^7gfx auto: LOW"
EOF
      ;;
    *)
      cat <<'EOF'
seta cl_renderer "vulkan"
seta r_bloom "1"
seta r_bloom_intensity "0.5"
seta r_bloom_threshold "0.6"
seta r_picmip "1"
seta r_ext_max_anisotropy "4"
seta r_texturemode "GL_LINEAR_MIPMAP_LINEAR"
seta r_dynamiclight "1"
seta r_flares "1"
seta r_fastsky "0"
seta r_vertexlight "0"
seta cg_shadows "1"
seta r_subdivisions "4"
seta com_maxfps "250"
seta r_swapInterval "0"
echo "^4NeonArena ^7gfx auto: MED"
EOF
      ;;
  esac
}

write_file() {
  local file="$1" preset="$2" name="$3"
  mkdir -p "$(dirname "$file")"
  preset_body "$preset" "$name" > "$file"
}

NAME=$(gpu_name)
VULKAN=0
have_vulkan && VULKAN=1
VRAM=$(vram_mb)
[ -n "$VRAM" ] || VRAM=0
PRESET=$(pick_preset "$NAME" "$VULKAN" "$VRAM")
if [ -n "${NW_GFX_PRESET:-}" ] && [ "${NW_GFX_PRESET}" != auto ]; then
  case "$NW_GFX_PRESET" in
    low|med|high) PRESET="$NW_GFX_PRESET" ;;
  esac
fi

MODE=print
OUT=""
FORCE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h) usage ;;
    --dump) MODE=dump; shift ;;
    --ensure)
      MODE=ensure
      OUT="${2:-}"
      [ -n "$OUT" ] || { echo "usage: --ensure FILE" >&2; exit 2; }
      shift 2
      ;;
    --write)
      MODE=write
      OUT="${2:-}"
      FORCE="${3:-}"
      [ -n "$OUT" ] && [ -n "$FORCE" ] || { echo "usage: --write FILE PRESET" >&2; exit 2; }
      shift 3
      ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

case "$MODE" in
  dump)
    echo "gpu: ${NAME:-unknown}"
    echo "vulkan: $VULKAN"
    echo "vram_mb: $VRAM"
    echo "preset: $PRESET"
    ;;
  ensure)
    if [ ! -f "$OUT" ]; then
      write_file "$OUT" "$PRESET" "${NAME:-unknown}"
    else
      got=$(grep -m1 '^// preset:' "$OUT" 2>/dev/null | awk '{print $3}' || true)
      [ -n "$got" ] && PRESET="$got"
    fi
    echo "$PRESET"
    ;;
  write)
    case "$FORCE" in low|med|high) ;; *) echo "preset must be low|med|high" >&2; exit 2 ;; esac
    write_file "$OUT" "$FORCE" "${NAME:-unknown}"
    echo "$FORCE"
    ;;
  *)
    echo "$PRESET"
    ;;
esac
